services:
  - type: web
    name: construction-career-survey
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: FIREBASE_CONFIG
        sync: false
    healthCheckPath: /
    autoDeploy: true
