services:
  - type: web
    name: construction-career-survey
    env: static
    buildCommand: npm install
    staticPublishPath: ./
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: FIREBASE_CONFIG
        sync: false
