services:
  - type: web
    name: construction-career-survey
    env: docker
    dockerfilePath: ./Dockerfile
    branch: production
    healthCheckPath: /health
    envVars:
      - key: FIREBASE_CONFIG
        sync: false
      - key: NODE_ENV
        value: production
    scaling:
      minInstances: 1
      maxInstances: 3
      targetMemoryPercent: 80
    autoDeploy: true
    domains:
      - construction-career-survey.onrender.com
